name: tests

on:
  push:
    branches-ignore: [gh-pages]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - stable
          - devel
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v3
      with:
        nimversion: ${{ matrix.version }}
    - name: Install deps
      run: |
        nimble refresh
        nimble install -y
    - name: Test
      run: nimble test
    - name: Examples
      run: |
        nim c -r examples/everything.nim
        nim c -r examples/color.nim
